# Generated by Django 6.0.5 on 2026-06-16 14:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок поста')),
                ('content', models.TextField(verbose_name='Контент поста')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2026, 6, 16, 14, 14, 51, 593032, tzinfo=datetime.timezone.utc), verbose_name='Дата создания поста')),
                ('edited', models.BooleanField(default=False, verbose_name='Редактирован ли?')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Название картинки')),
                ('file', models.FileField(upload_to='images/', verbose_name='Файл')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Картинка поста',
                'verbose_name_plural': 'Картинки постов',
            },
        ),
    ]
