# Generated by Django 6.0.5 on 2026-06-16 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 16, 14, 15, 47, 821274, tzinfo=datetime.timezone.utc), verbose_name='Дата создания поста'),
        ),
    ]
