# Generated by Django 6.0.5 on 2026-06-16 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 16, 14, 16, 24, 67347, tzinfo=datetime.timezone.utc), verbose_name='Дата создания поста'),
        ),
    ]
